name: Gen time

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - '*'

env:
  home: '/home/runner/.config'

jobs:
  heap_memory_usage:
    name: Heap memory usage
    runs-on: macos-latest
    steps:
    
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: |
          chmod +x gradlew
          ./gradlew installDebug

    - name: Launch app
      run: |
        sleep 2
        adb shell am start -n com.example.githubactionssampleproject4/com.example.githubactionssampleproject4.MainActivity

    - name: Print heap memory usage
      run: |
        memory_info="$(adb shell dumpsys meminfo com.example.githubactionssampleproject4)"
        printf "%15s %15s %15s %15s\n" "" "Heap Size" "Heap Alloc" "Heap Free"
        printf "%15s %15s %15s %15s\n" "" "---------" "----------" "---------"
        echo "$memory_info" | grep "Native Heap" | head -1 | awk '{printf "%15s %15d %15d %15d\n", "Native Heap", $8, $9, $10}'
        echo "$memory_info" | grep "Dalvik Heap" | head -1 | awk '{printf "%15s %15d %15d %15d\n", "Dalvik Heap", $8, $9, $10}'
        echo "$memory_info" | grep "TOTAL" | head -1 | awk '{printf "%15s %15d %15d %15d\n", "TOTAL", $7, $8, $9}'
